### ISSUE TITLE
Suggestion: Add lecture on SQL

### ISSUE THREAD

**Issue by treilly** [DaveBackus/Data_Bootcamp#1]
Hi Dave,

Your posts today led me here.  Reading the syllabus you've posted here, I'd urge you to add a lecture on SQL as it's by far the most common source of data in a corporate environment.

In my experience, work breaks down as:
1) Get data
2) Transform data
3) Explore data
4) Model data
5) Generate graphs/figures
6) Present analysis

For me, SQL's a critical piece of 1, 2, and sometimes 3.

Best,

-Tim

**Comment by DaveBackus** [comment]
We'll build this into the course.  In the meantime, we're running a short course to get students ready for summer internships.  https://github.com/DaveBackus/Data_Bootcamp#sql-bootcamp
