### ISSUE TITLE
website

### ISSUE THREAD

**Issue by DaveBackus** [DaveBackus/Data_Bootcamp#11]
I've created a directory called Markdown and put a few files in it that should serve as the basis for a course website.  Links to other pages are relative.  

The question is how we want to set up the course website.  Use this way, or use these inputs to create something nicer?  Thoughts welcome.

**Comment by spencerlyon2** [comment]
Very cool. I'll play around with the [system I like to use](http://gohugo.io) to build websites from markdown and let you take a look to see if you like it.

**Comment by DaveBackus** [comment]
Can we work directly with the md files going forward?  Or do we change them
and work with new files?

**Comment by spencerlyon2** [comment]
All the content will be derived directly from the markdown files. If we
edit them, the site will change accordingly

// Spencer

**Comment by DaveBackus** [comment]
Some things to think about, but not to do, at least not yet.  None of them important.  
The link fyi:  http://databootcamp.nyuecon.com/

* Add space below the title.  What's there is probably my suggestion, but I now think we want to return to the original format.  

* Increase font size on footer.  

* Shrink right margin of navigation panel.

**Comment by spencerlyon2** [comment]
Response to the points:

- So you want to kill the `Data + Python @ NYU Stern`?
- Will do
- Will do

**Comment by spencerlyon2** [comment]
We might want to iterate on point 3. 

Do you just want the purple part to be more narrow? What if that splits the `Data Bootcamp` to 2 lines, are you ok with that?

**Comment by DaveBackus** [comment]
Yes on 2 and 3.

On 1 I had something different in mind:  Add space after the headings.  I
think I suggested we kill it, but now the subhead is squeezed right up
against the heading.

http://databootcamp.nyuecon.com/

So I'd like to have a heading, then skip some space, then whatever comes
next.

**Comment by spencerlyon2** [comment]
This contains a `<br>` between the title and subtitle as well as larger footer font. What do you think?

<img width="1440" alt="screen shot 2016-01-08 at 10 40 17 am" src="https://cloud.githubusercontent.com/assets/1001948/12204878/516a15d4-b5f4-11e5-87f4-1aa5de4e655b.png">


We should still iterate on making the margin smaller.

**Comment by DaveBackus** [comment]
Can we talk?

**Comment by spencerlyon2** [comment]
Should be live now
