### ISSUE TITLE
Cannot run anything in SQL_Intro file

### ISSUE THREAD

**Issue by jchoe415** [DaveBackus/Data_Bootcamp#7]
I have been running the SQL_Intro file without any problems in the past. I went back to it for review today. After selecting run all, I noticed that none of the line items (in [ ]) had numbers in the brackets. Any time I enter a prompt, I don't get the proper outputs. I'm pretty certain I haven't installed any apps or anything that would've change settings on my computer.

Here's an example:

run('''
    PRAGMA TABLE_INFO(sales_table)
    ''')

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-2-ed8a089df8de> in <module>()
----> 1 run('''
      2     PRAGMA TABLE_INFO(sales_table)
      3     ''')

NameError: name 'run' is not defined

I am running Anaconda (Py 3.4) on a Windows 7 device.

Thank you.
![error](https://cloud.githubusercontent.com/assets/12054066/8992929/8afffea2-36cf-11e5-9414-8526a31ed8ec.JPG)

**Comment by DaveBackus** [comment]
So you changed nothing on your computer and now it doesn't run?  Hard to
see what that has to do with the repo.  Or is it something else?

One problem people had in the past was they were missing a file that ran in
the background.  This code checks to see if that's the case:

import os


file = 'SQL_support_code.py'

if not os.path.isfile(file):

    raise Exception('***** Program halted, file missing *****')

**Comment by jchoe415** [comment]
The support code file has been in the same folder. I tried downloading both
raw files to a new folder and I am still seeing the issue.

**Comment by DaveBackus** [comment]
Ok, you should be good.  The support code reads csv files that we
accidentally eliminated from the repo.
