### ISSUE TITLE
wireless access in the classroom

### ISSUE THREAD

**Issue by DaveBackus** [DaveBackus/Data_Bootcamp#9]
We should check this:
* If we have 50 people in a classroom downloading Anaconda, will the system be overloaded?
* Also what to do with non-Stern students -- can we get a guest account?  Instructions for them to start their Stern account?

**Comment by ravenswoodnyc** [comment]
Why not just have a handful of thumb drives with anaconda installed? Or a
network location with the zip installer?

**Comment by DaveBackus** [comment]
Ah, thank you, good thought.  Great to have help!

**Comment by DaveBackus** [comment]
USB drives in hand, team is loading Anaconda installer on them.
